version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "terraform"
    directories:
      - "/"
      - "/module/s3"
      - "/module/cloudfront"
      - "/module/certificate-manager"
      - "/module/route53"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      terraform-fix:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "terraform"
    directories:
      - "/"
      - "/module/s3"
      - "/module/cloudfront"
      - "/module/certificate-manager"
      - "/module/route53"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "feat"
      include: "scope"
    groups:
      terraform-feat:
        patterns:
          - "*"
        update-types:
          - "major"
