name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
      - 'feat!'
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'deps'
  - title: '📝 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚙️ CI/CD'
    labels:
      - 'ci'
      - 'ci/cd'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
      - 'feat!'
  minor:
    labels:
      - 'minor'
      - 'feat'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'chore'
      - 'deps'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: 'feat'
    title:
      - '/^feat(\(.+\))?:.+$/i'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?:.+$/i'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?:.+$/i'
  - label: 'docs'
    title:
      - '/^docs(\(.+\))?:.+$/i'
  - label: 'ci'
    title:
      - '/^ci(\(.+\))?:.+$/i'
  - label: 'breaking'
    title:
      - '/^feat(\(.+\))?!:.+$/i'
      - '/BREAKING CHANGE/i'
  - label: 'deps'
    branch:
      - '/^dependabot\/.+$/i'
    title:
      - '/^(build|chore)\(deps\):.+$/i'
