name: PR Validation

on:
  pull_request:
    branches: [main, master]
    paths:
      - "**.tf"
      - "**.tfvars"
      - ".github/workflows/pr-check.yml"

jobs:
  terraform-check:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.5

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
