name: Release

on:
  release:
    types: [published] # Trigger when draft release is manually published
  workflow_dispatch: # Allow manual trigger for testing

permissions:
  contents: read

jobs:
  validation:
    name: Terraform Validation
    uses: ./.github/workflows/validate-terraform.yml

  security-scan:
    name: Security Scanning
    uses: ./.github/workflows/security-scan.yml
    permissions:
      contents: read
      security-events: write

  finalize-release:
    name: Finalize Release
    runs-on: ubuntu-latest
    needs: [validation, security-scan]
    permissions:
      contents: write
      pull-requests: write
      security-events: write
    outputs:
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_PUSH_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_PUSH_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@9cc899c47e6841430bbaedb43de1560a568dfd16 # v5.0.0
        with:
          semantic_version: 23.0.2
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  publish-oci:
    name: Publish OCI Module
    needs: finalize-release
    if: needs.finalize-release.outputs.new_release_version != ''
    uses: ./.github/workflows/publish-oci.yml
    with:
      package_name: terraform-aws-static-site-s3-https
      release_version: ${{ needs.finalize-release.outputs.new_release_version }}
    permissions:
      attestations: write
      contents: write
      id-token: write
      packages: write
      actions: read
