name: Release

on:
  push:
    branches: [main]
    paths:
      - "**.tf"
      - "**.tfvars"
      - ".github/workflows/release.yml"

permissions:
  contents: write
  pull-requests: write
  security-events: write

jobs:
  validation:
    name: Validation
    uses: ./.github/workflows/validation.yml

  security-scan:
    name: Security Scanning
    uses: ./.github/workflows/security-scan.yml

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [validation, security-scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v5
        with:
          semantic_version: 23.0.2
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@7.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
