name: Security Scan

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_call:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  comprehensive-security-scan:
    name: Comprehensive Security Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ~1.5

      - name: Initialize Terraform
        run: terraform init

      - name: Run Checkov IaC Security Scan
        id: checkov
        uses: bridgecrewio/checkov-action@252558a0a63b7d3e9aec0342c208e9fe280ed345 # master
        with:
          output_format: sarif
          output_file_path: checkov-results.sarif
          quiet: false
          soft_fail: false
          config_file: .checkov.yml

      - name: Upload Checkov results to GitHub Security
        uses: github/codeql-action/upload-sarif@64d10c13136e1c5bce3e5fbde8d4906eeaafc885 # v3.30.6
        if: always()
        with:
          sarif_file: checkov-results.sarif

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          scanners: "vuln,secret"

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@64d10c13136e1c5bce3e5fbde8d4906eeaafc885 # v3.30.6
        if: always()
        with:
          sarif_file: trivy-results.sarif

      - name: Run Semgrep Security Analysis
        uses: returntocorp/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d # v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/terraform
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Generate Security Report Summary
        if: always()
        run: |
          echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Scans Performed:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Checkov (IaC Security)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Trivy (Vulnerability & Secret Scanning)" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Semgrep (SAST Security Analysis)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Security scan results have been uploaded to GitHub Security tab." >> $GITHUB_STEP_SUMMARY
